"""another revision

Revision ID: f2607cbdb9ab
Revises: 9b196653a126
Create Date: 2026-07-01 16:16:00.854521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2607cbdb9ab'
down_revision: Union[str, Sequence[str], None] = '9b196653a126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.Enum('SOLIDARIO', 'PROFESIONAL', 'ESPECIALIZADO', name='userrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
